module.exports =
[ 'Aberdeenshire'
, 'Angus'
, 'Argyllshire'
, 'Ayrshire'
, 'Banffshire'
, 'Berwickshire'
, 'Buteshire'
, 'Caithness'
, 'Clackmannanshire'
, 'Cromartyshire'
, 'Dumfriesshire'
, 'Dunbartonshire'
, 'East Lothian'
, 'Fife'
, 'Inverness-shire'
, 'Kincardineshire'
, 'Kinross-shire'
, 'Kirkcudbrightshire'
, 'Lanarkshire'
, 'Midlothian'
, 'Morayshire'
, 'Nairnshire'
, 'Orkney'
, 'Peeblesshire'
, 'Perthshire'
, 'Renfrewshire'
, 'Ross-shire'
, 'Roxburghshire'
, 'Selkirkshire'
, 'Shetland'
, 'Stirlingshire'
, 'Sutherland'
, 'West Lothian'
, 'Wigtownshire'
]
