module.exports =
[ 'Anglesey'
, 'Brecknockshire'
, 'Caernarfonshire'
, 'Carmarthenshire'
, 'Cardiganshire'
, 'Denbighshire'
, 'Flintshire'
, 'Glamorgan'
, 'Merioneth'
, 'Monmouthshire'
, 'Montgomeryshire'
, 'Pembrokeshire'
, 'Radnorshire'
]
